name: ncrystal_devel
channels:
  - nodefaults
  - conda-forge
dependencies:
  - c-compiler
  - cmake
  - cppcheck
  - cxx-compiler
  - mpmath
  - numpy >=1.22
  - pip
  - pybind11
  - python
  - pyyaml
  - ruff >=0.8.0
  - simple-build-system >=1.6.0
  - tomli
