name: ncrystal_all
channels:
  - nodefaults
  - conda-forge
dependencies:
  - ase <3.24.0
  - c-compiler
  - cmake
  - cxx-compiler
  - gemmi
  - matplotlib
  - numpy >=1.22
  - pip
  - python
  - spglib
