name: ncrystal_all_combined
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - compilers
  - cmake
  - numpy
  - pip
  - ase<3.24.0
  - cppcheck
  - gemmi
  - matplotlib
  - mpmath
  - numpy
  - pybind11
  - ruff
  - simple-build-system
  - spglib
  - tomli
