name: ncrystal_all_combined
channels:
  - nodefaults
  - conda-forge
dependencies:
  - ase <3.24.0
  - c-compiler
  - cmake
  - cppcheck
  - cxx-compiler
  - gemmi
  - matplotlib
  - mpmath
  - numpy >=1.22
  - pip
  - pybind11
  - python
  - pyyaml
  - ruff
  - simple-build-system
  - spglib
  - tomli
