name: ncrystal_devel
channels:
  - nodefaults
  - conda-forge
dependencies:
  - c-compiler
  - cmake
  - cppcheck
  - cxx-compiler
  - mpmath
  - numpy >=1.22
  - pip
  - pybind11
  - python
  - ruff
  - simple-build-system
  - tomli
