[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ncrystal"
version = "3.9.85"
requires-python = ">=3.8"
dependencies = [ 'ncrystal-core==3.9.85', 'ncrystal-python==3.9.85' ]
authors = [
  { name="NCrystal developers (Thomas Kittelmann, Xiao Xiao Cai)" },
]
description = "Library for thermal neutron transport in crystals and other materials."
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

[project.urls]
"Homepage" = "https://mctools.github.io/ncrystal/"
"Bug Tracker" = "https://github.com/mctools/ncrystal/issues"

[project.optional-dependencies]
composer = [ 'spglib' ]
cif = [ 'ase<3.24.0', 'gemmi', 'spglib' ]
plot = [ 'matplotlib' ]
all = [ 'ase<3.24.0', 'gemmi', 'spglib', 'matplotlib' ]
devel = [ 'simple-build-system', 'ruff', 'pyyaml', 'cppcheck', 'mpmath', 'tomli', 'pybind11' ]
