name: ncrystaltestenv
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - compilers
  - cmake
  - numpy
  - pip
#  - geant4
#  - expat
#  - ase
#  - pymatgen
#  - matplotlib
#  - gemmi
#  - spglib
#  - scipy
#NOT THIS OR ANYTHING USING IT!:  - ncrystal
