name: c_cpp_standards

on:
  push:
  pull_request:
  schedule:
    - cron: '10 15 * * 0'  # 10:15 every Sunday

jobs:
  build:
    strategy:
      matrix:
        strictflag: [11, 14, 17, 20, 23]
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: ${{ matrix.os }}.strict${{ matrix.strictflag }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Configure CMake
      run: >
        cmake -S ./src -B ./build
        -DCMAKE_INSTALL_PREFIX=./install
        -DNCRYSTAL_ENABLE_EXAMPLES=ON
        -DNCRYSTAL_BUILD_STRICT=${{ matrix.strictflag }}

    - name: Build
      run: cmake --build ./build --config Release
