name: essncrystaldev-short
on:
  push:
  pull_request:
  schedule:
    - cron: '30 8 * * 2'  # 8:30 every Tuesday

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, CC: gcc,      CXX: g++,        python: '3.13' }
          - { os: macos-latest,  CC: clang,    CXX: clang++,    python: "3.11" }
    name: ${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CONDA_SOLVER: libmamba

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./src

      - name: Checkout ncrystaldev
        env:
          THEACCESSTOKEN: ${{ secrets.ACCESS_TOKEN_NCRYSTALDEV }}
        run: |
          set -eu
          test "${THEACCESSTOKEN:-}" != "" || ( echo "Access token missing"; exit 1 )
          git clone --depth=1 'https://usernamedoesnotmatter:'"${THEACCESSTOKEN}"'@git.esss.dk/ncrystal/ncrystaldev.git' ./src_ncrystaldev

      - name: Set up conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ncrystal_all_combined
          environment-file: ./src/devel/reqs/conda_all_and_devel.yml
          auto-activate-base: false

      - name: Install more dependencies
        run: conda install simple-build-dgcode zlib h5py

      - name: Install ncrystaldev simplebuild discovery package
        run: pip install -e ./src_ncrystaldev/discovery

      - name: Install ncrystaldynamic simplebuild discovery package
        run: pip install -e ./src/devel/simplebuild/discovery

      - name: Prepare simplebuild cfg
        run: cp src/.github/resources/simplebuild_ncrystaldev.cfg ./simplebuild.cfg && mkdir dummy

      - name: Build
        run: sb -v

      - name: Run sb_nctests_testuids
        run: sbenv sb_nctests_testuids

      - name: Launch tests
        run: sb -t --testexcerpts=500 --requirepkg=NCTestAll,NCTests --testfilter='!sb_nclong*'
