name: pypi_test

on:
  push:
    tags:
      - 'tktest[0-9]+.[0-9]+.[0-9]+'

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Pip install packages
        run: pip install cibuildwheel ruff

      - name: ncdevtool checks
        run: ./src/devel/bin/ncdevtool check -n fixme

      - name: Verify version number
        id: version-number
        run: |
          set -eux
          VERSIONSTR=$(./src/devel/bin/ncdevtool verifytag -p 'tktestX.Y.Z' --fail-if-devel --file-verify=VERSION)
          echo "version_number=$VERSIONSTR" >> $GITHUB_OUTPUT

      - name: Echo tag version number
        env:
          ENV_VERSION_NUMBER: ${{ steps.version-number.outputs.version_number }}
        run: |
          echo A=$ENV_VERSION_NUMBER
          echo B=${{ steps.version-number.outputs.version_number }}
